;;; custom.el -*- lexical-binding: t; -*-

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(elfeed-feeds
   '("https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw"
     ("https://archive.casouri.cat/note/rss.xml")
     ("https://rsshub.autove.dev/smzdm/ranking/haowen/yc/48?key=Melt" leisure
      news buy)
     ("https://rsshub.autove.dev/natgeo/environment/article?key=Melt" leisure
      news)
     ("https://rsshub.autove.dev/natgeo/dailyphoto?key=Melt" leisure news)
     ("https://medium.com/feed/boox-content-hub" leisure news)
     ("https://rsshub.autove.dev/nytimes/en?key=Melt" leisure news)
     ("https://rsshub.autove.dev/zaobao/znews/world?key=Melt" leisure news)
     ("https://rsshub.autove.dev/zaobao/znews/china?key=Melt" leisure news)
     ("https://rsshub.autove.dev/zaobao/realtime/world?key=Melt" leisure news)
     ("https://rsshub.autove.dev/zaobao/realtime/china?key=Melt" leisure news)
     ("https://rsshub.autove.dev/ft/chinese/hotstoryby7day" leisure news)
     ("https://rsshub.autove.dev/engadget-cn?key=Melt" leisure news tech)
     ("https://rsshub.autove.dev/cnbeta?key=Melt" leisure news tech)
     ("https://rsshub.autove.dev/zhihu/daily" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/37166127" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/45382427" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/20094118" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/23186304" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/19825336" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/64483355" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/44434804" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/40631599" zhihu leisure)
     ("https://rsshub.autove.dev/zhihu/collection/427264591" zhihu leisure)
     ("https://rsshub.autove.dev/jdlingyu/tuji" anime leisure)
     ("https://rsshub.autove.dev/yande.re/post/popular_recent/1d" anime leisure)
     ("https://rsshub.autove.dev/konachan.net/post/popular_recent/1d" anime
      leisure)
     ("https://rsshub.autove.dev/pixiv/ranking/week" anime leisure)
     ("https://rsshub.autove.dev/bilibili/user/video/3907165" anime leisure)
     ("https://rsshub.autove.dev/bilibili/user/video/411462" anime leisure)
     ("https://rsshub.autove.dev/bilibili/user/video/580315930" food leisure)
     ("https://rsshub.autove.dev/bilibili/user/video/290526283" food leisure)
     ("https://rsshub.autove.dev/bilibili/user/video/415479453" food leisure)
     ("https://rsshub.autove.dev/bilibili/user/video/419872064" food leisure)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCg0m_Ah8P_MQbnn77-vYnYw"
      food leisure)
     ("https://farseerfc.me/feeds/atom.xml") ("http://scateu.me/feed.xml")
     ("https://bigeagle.me/index.xml") ("https://jherrlin.github.io/index.xml")
     ("https://planet.emacslife.com/atom.xml" emacs)
     ("http://export.arxiv.org/api/query?search_query=cat:cs.CC&start=0&max_results=300&sortBy=submittedDate&sortOrder=descending"
      research)
     ("http://export.arxiv.org/api/query?search_query=cat:cs.DS&start=0&max_results=300&sortBy=submittedDate&sortOrder=descending"
      research)
     ("http://cstheory-feed.org/atom.xml" research)
     ("https://rsshub.autove.dev/apple/podcast/id1559695855" reeder)
     ("https://rsshub.autove.dev/github/activity/sindresorhus" reeder)
     ("https://rsshub.autove.dev/github/topics/investment-analysis/o=desc&s=stars"
      reeder)
     ("https://rsshub.autove.dev/github/topics/writing/s=starts&o=desc" reeder)
     ("https://rsshub.autove.dev/github/topics/awesome/o=desc&s=stars" reeder)
     ("https://rsshub.autove.dev/github/topics/math/s=stars&o=desc" reeder)
     ("https://rsshub.autove.dev/github/topics/haskell/o=desc&s=stars" reeder)
     ("https://rsshub.autove.dev/github/topics/emacs/s=starts&o=desc" reeder)
     ("https://rsshub.autove.dev/github/topics/kernel" reeder)
     ("https://rsshub.autove.dev/twitter/user/SpaceX" reeder)
     ("https://rsshub.autove.dev/twitter/user/HotmailfromSH/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/elonmusk" reeder)
     ("https://rsshub.autove.dev/twitter/user/sehviyat" reeder)
     ("https://rsshub.autove.dev/twitter/user/EssentialMastry/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/feltanimalworld/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/greendreaams/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/whyyoutouzhele/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/CctvCamera69716" reeder)
     ("https://rsshub.autove.dev/twitter/user/N0rthern_Land/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/didengshengwu/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/wuhanomad/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/Morris_LT" reeder)
     ("https://rsshub.autove.dev/twitter/user/surdicated/feed" reeder)
     ("https://rsshub.autove.dev/twitter/user/435hz/feed" reeder)
     ("https://rsshub.autove.dev/twitter/media/mugoushesijihua" reeder)
     ("https://rsshub.autove.dev/twitter/user/mugoushesijihua" reeder)
     ("https://rsshub.autove.dev/economist/finance-and-economics" reeder)
     ("https://rsshub.autove.dev/economist/china" reeder)
     ("https://rsshub.autove.dev/economist/asia" reeder)
     ("https://rsshub.autove.dev/zhihu/people/activities/retrive" reeder)
     ("https://rsshub.autove.dev/zhihu/hot/car" reeder)
     ("https://rsshub.autove.dev/zhihu/hot/total" reeder)
     ("https://rsshub.autove.dev/xueqiu/hots" reeder)
     ("https://rsshub.autove.dev/v2ex/xna" reeder)
     ("https://rsshub.autove.dev/51cto/index/recommend" reeder)
     ("http://www.4sbooks.com/feed" reeder)
     ("https://coolshell.cn/feed.xml/feed" reeder)
     ("http://www.geekpark.net/rss" reeder news)
     ("https://rsshub.autove.dev/weibo/user/2915005333?key=Melt" social weibo)
     ("https://rsshub.autove.dev/weibo/user/3189842472?key=Melt" social weibo)
     ("https://rsshub.autove.dev/weibo/user/2966002294?key=Melt" social weibo)
     ("https://rsshub.autove.dev/weibo/user/1834459124?key=Melt" social weibo)
     ("https://rsshub.autove.dev/twitter/user/xiangjiaoguomin?key=Melt" social
      twitter)
     ("https://rsshub.autove.dev/smzdm/ranking/pinlei/11/3?key=Melt" lifestyle
      shopping)
     ("https://feedx.net/rss/shanghaishuping.xml" lifestyle reading)
     ("https://rsshub.autove.dev/youtube/user/@laodongbeimeishi?key=Melt"
      lifestyle cooking video)
     ("https://rsshub.autove.dev/youtube/channel/UCt1g7JuMPxb1NYRvn3JCA4Q?key=Melt"
      media music)
     ("https://rsshub.autove.dev/bilibili/partion/146?key=Melt" media)
     ("https://rsshub.autove.dev/douban/movie/later?key=Melt" media)
     ("https://rsshub.autove.dev/youtube/channel/UCy-dvmsfmvYXBmt_huqqo1A?key=Melt"
      media)
     ("https://rsshub.autove.dev/youtube/channel/UCYO_jab_esuFRV4b17AJtAw?key=Melt"
      media)
     ("https://rsshub.autove.dev/youtube/channel/UCRjfqDnltvniD5CUvv14DOg?key=Melt"
      media)
     ("https://rsshub.autove.dev/youtube/channel/UCZ_HHuwxpqXGlTOFx1veVdw?key=Melt"
      media)
     ("https://rsshub.autove.dev/youtube/channel/UCq2a8muf_TCGJt1AhBfU-7A?key=Melt"
      media)
     ("https://rsshub.autove.dev/wsj/en-us/market_news" news finance)
     ("https://rsshub.autove.dev/whu/news/wdyw?key=Melt" news)
     ("http://www.ruanyifeng.com/blog/atom.xml" news)
     ("https://lobste.rs/rss" news) ("https://hnrss.org/frontpage" news)
     ("https://news.ycombinator.com/rss" news)
     ("https://www.yinwang.org/atom.xml" blog blog)
     ("https://feedpress.me/wx-youyouluming" blog weixin)
     ("https://feedpress.me/wx-quiet-desk" blog weixin)
     ("https://feedpress.me/wx-girlswhocode" blog weixin)
     ("https://endler.dev/rss.xml" blog) ("https://jvns.ca/atom.xml" blog)
     ("https://simonwillison.net/atom/entries/" blog)
     ("http://www.matrix67.com/blog/feed" blog)
     ("http://www.aaronsw.com/2002/feeds/pgessays.rss" blog)
     ("http://blog.codingnow.com/atom.xml" blog)
     ("https://www.inoreader.com/feed/https%3A%2F%2Fcatman.app%2Ffeed.xml" blog
      immigration)
     ("https://blog.lilydjwg.me/feed" blog)
     ("https://rsshub.autove.dev/blogs/wangyin?key=Melt" blog)
     ("http://rss.arxiv.org/rss/cs" ai research)
     ("https://research.google/blog/rss/" ai research)
     ("https://3blue1brown.substack.com/feed.xml" ai research math)
     ("https://openai.com/news/rss.xml" ai research)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCbCCUH8S3yhlm7__rhxR2QQ"
      programming network video)
     ("https://bulianglin.com/feed/" programming network blog)
     ("https://rsshub.autove.dev/bulianglin?key=Melt" programming network video)
     ("https://rsshub.autove.dev/youtube/channel/UC5xDNEcvb1vgw3lE21Ack2Q"
      programming algorithm video)
     ("https://rsshub.autove.dev/leetcode/articles?key=Melt" programming)
     ("https://haskellweekly.news/newsletter.atom" programming)
     ("https://planet.haskell.org/rss20.xml" programming)
     ("https://blog.python.org/rss.xml" programming)
     ("https://this-week-in-rust.org/atom.xml" programming)
     ("https://blog.rust-lang.org/feed.xml" programming)
     ("https://sachachua.com/blog/feed/" emacs)
     ("http://melt.autove.dev/atom.xml" emacs)
     ("http://blog.binchen.org//rss.xml" emacs)
     ("https://emacs-china.org/latest.rss" emacs)
     ("https://www.zmonster.me/microblog-feed.xml" emacs)
     ("https://www.zmonster.me/atom.xml" emacs)
     ("https://archive.casouri.cat/note/rss.xml" emacs)
     ("https://manateelazycat.github.io/feed.xml" emacs)
     ("https://github.blog/changelog/feed/" system opensource)
     ("https://forum.suse.org.cn/latest.rss" system opensource)
     ("https://archlinux.org/feeds/news/" system opensource)
     ("https://discourse.nixos.org/c/announcements/8.rss" system opensource)
     ("https://lwn.net/headlines/rss" system opensource)))
 '(safe-local-variable-directories
   '("/mnt/home/wd/.hikyuu/hub_cache/default/" "/home/wd/.config/emacs.d/"
     "/home/wd/.config/emacs")))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-block ((t (:inherit fixed-pitch))))
 '(org-code ((t (:inherit (shadow fixed-pitch)))))
 '(org-document-info ((t (:foreground "dark orange"))))
 '(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
 '(org-indent ((t (:inherit (org-hide fixed-pitch)))))
 '(org-link ((t (:foreground "royal blue" :underline t))))
 '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch)))))
 '(org-property-value ((t (:inherit fixed-pitch))))
 '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
 '(org-table ((t (:inherit fixed-pitch :foreground "#83a598"))))
 '(org-tag ((t (:inherit (shadow fixed-pitch) :weight bold :height 0.8))))
 '(org-verbatim ((t (:inherit (shadow fixed-pitch))))))
