* Vocabulary
** formfeed [fɔrm'fid]
n. 换页 | 网络 进纸；进纸键；进纸符
** relaxation [ˌrilækˈseɪʃ(ə)n]
n. 放松；消遣；休息；用于放松消遣的时间 | 网络 松弛；娱乐；缓和
** trient 
网络 特兰托市；特伦托；特里恩
** locus [ˈloʊkəs]
n. （某事发生的）确切地点；（被视为某物的）中心 | 网络 轨迹；基因座；位点
** conceal [kənˈsil]
v. 隐藏；隐瞒；掩盖 | 网络 隐蔽；把…隐藏起来；掩饰
** overlaid [ˈoʊvərˌleɪ]
v. 覆；包；涂；弄阴 | n. 【印】轮廓纸；上衬；盖在上面的东西；被单 | 网络 覆盖；被覆盖；覆加的
** Graphical [ˈɡræfɪk(ə)l]
adj. 图形的；计算机图形的；用图（或图表）表示的 | 网络 图解的；绘画的；图形型
** Interface [ˈɪntərˌfeɪs]
n. 接口；（人机）界面（尤指屏幕布局和选单）；接口程序；连接电路 | v. 连接 | 网络 介面；分界面；接口类型
** hollow [ˈhɑloʊ]
n. 孔；洞；凹陷处；坑洼处 | v. 挖 | adj. 中空的；空心的；凹陷的；沉闷回荡的 | adv. 彻底 | 网络 空洞的；空虚道
** inferior [ɪnˈfɪriər]
adj. 较差的；次的；比不上…的；级别低的 | n. 不如别人的人；级别（或地位）低的人 | 网络 下级的；劣等的；下等的
** elapse [ɪˈlæps]
v. 流逝 | n. (时间的)消逝 | 网络 过去；逝去；经过
** ferrite ['feraɪt]
n. 铁氧体（用于制作天线等电气设备）；（存在于钢中的）铁素体 | 网络 肥粒铁；纯铁体；铁氧体永磁材料
** pertinent [ˈpɜrt(ə)nənt]
adj. 有关的；恰当的；相宜的 | n. 附属物；参考 | 网络 中肯的；相关的；相干的
** kludge [kludʒ]
n. 不成熟产品；蹩脚系统 | 网络 杂牌电脑；拙集；拼凑
** crept [krip]
n. 爬行；徐行；蠕动；【印,纺】蠕变 | v. 爬行；(病人,老者)衰弱迟缓地前进；蠕动；【印,纺】蠕变 | abbr. (=Committee for the Reelection of the President)(美国)支持总统连任委员会 | 网络 蔓延；蹑手蹑脚地；动词过去分词
** Harvard [ˈhɑrvərd]
n. (美国)哈佛大学；哈佛大学学生[毕业生] | 网络 哈佛总线；私立哈佛大学；哈福工业公司
** vanilla [vəˈnɪlə]
adj. 有香子兰香味的；香草味的；普通的；寻常的 | n. 香草醛 | 网络 香草精；香草兰；香草冰淇淋
** variable-pitch  
n. 变节距 | 网络 变桨距；变宽
** mathematica 
网络 数学软件；软件及其模块；之附加程序
** mathematics [ˌmæθəˈmætɪks]
n. 数学；运算；计算 | 网络 数学系；数学专业；数学类
** embedded [ɪmˈbed]
v. 埋置；【医】植入；栽种；深留(记忆中) | 网络 嵌入式；内嵌；嵌入的
** traveling [ˈtræv(ə)l]
v. 旅游；旅行；传播；运行 | n. 旅游；旅行；游历 | 网络 走步；无限漫游；移动
** 思想 [sī xiǎng] 
na. thought; ideology; thinking; idea | 网络 concept; mind; thoughts
